name: CI/CD with Minikube
#
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Minikube Kubeconfig
        run: |
          echo "$KUBE_CONFIG" > kubeconfig.yaml
          mkdir -p ~/.kube
          cp kubeconfig.yaml ~/.kube/config

      - name: Deploy to Minikube
        run: kubectl apply -f k8-app/
