name: Update JIRA Confluence Page
on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
env:
  JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
  JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
  CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
  
jobs:
  update_jira_confluence:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2   
    - name : Get Pull Request Details
      run: |
       PR_TITLE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | \
                 jq -r '.title')
            PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                       https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | \
                       jq -r '.body')
        env:
        PR_TITLE: ${{ env.PR_TITLE }}
        PR_DESCRIPTION: ${{ env.PR_DESCRIPTION }}
