name: Update JIRA
on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
env:
  JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
  JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
  CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
  
jobs:
  update_jira_confluence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: installing jq
        run: sudo apt-get install jq
      - name : Get Pull Request Details
        run: |
          PR_TITLE=$(curl -s -H "Authorization: Bearer ${{ secrets.RELEASE_GIT_TOKEN }}" \
                 https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | \
                 jq -r '.title')
          PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.RELEASE_GIT_TOKEN }}" \
                       https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | \
                       jq -r '.body')
        env:
          PR_TITLE: ${{ env.PR_TITLE }}
          PR_DESCRIPTION: ${{ env.PR_DESCRIPTION }}
      - name: Push Data to Confluence
        run: |
          PAGE_ID="393217"
          TABLE_CONTENT="||Title||Description||\n|${{ env.PR_TITLE }}|${{ env.PR_DESCRIPTION }}|"

          curl -s -u jadhavabhijeet6411@gmail.com:ATATT3xFfGF052_DMh9LgjLPKqujqP3NF-OnJzskWwvcwpe1ZwHYECj6LhCzyQbxWP5d6grUoB8CMVm73I9cEycFXZZkaV33y-USSBHpXWa7YG3vZ1JVFGSv3sClAR835y80viY4p9dywxYi_fUEb5d2KW2vn7ZGT2nPNPcWkJXIEv09DbUg3NA=F0CAEB1F \
            -X PUT \
            -H "Content-Type: application/json" \
            -d '{
               "version": {
                 "number": 1
                  },
               "title": "PR requests",
               "type": "page",
               "body": {
                 "storage": {
                 "value": "<table>${TABLE_CONTENT}</table>",
                 "representation": "storage"
                 }
               }
            }' \
          https://demo-sw.atlassian.net/wiki/rest/api/content/393217
